# Generated by Django 4.2.7 on 2024-09-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Web Development', 'WB'), ('Desktop Development', 'DB')], default='WB', max_length=20),
            preserve_default=False,
        ),
    ]
